### ISSUE TITLE
01 Structure/Navbar

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#1]
### Value Proposition

**As a**  User
 **I need** to navigate between the pages
**to be able** to see the content of the pages

### Description

<img width="272" alt="Bildschirmfoto 2022-11-28 um 11 53 43" src="https://user-images.githubusercontent.com/110241401/204260299-63182fce-5bb5-497e-aeb2-8808cc070ed2.png">

### Acceptance Criteria

- [ ] basic structure and adjustments for the beginning of the project done
- [ ] navigation bar is fixed at the bottom of the screen
- [ ] the  navbar includes 4 links and 1 button (connect Metamask)
- [ ] navelements should link to different pages
- [ ] if navelement is active, it should be highlighted (see the picture)

### Tasks

- [x] create basic structure of the project
- [x] create a new branch **feature/navbar**
- [x] start creating navigation bar (see picture in the description)
- [x] link the navelements to the pages
- [x] commit the changes 

### Sizing/Complexity

**S**
