### ISSUE TITLE
08 News Filter

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#16]
### Value Proposition

**As a** User
**I need** to be able to filter the news by specific cryptocurrency 
**to be able to** have my own overview about the specific information I need.

### Description

![IMG_5013](https://user-images.githubusercontent.com/110241401/206714822-3f916200-63f3-42be-8bd1-119ca5250da5.jpg)

### Acceptance Criteria

- [x] dropdown select element 
- [x] possibility to filter news by specific cryptocurrency
- [x] if user select a certain coin, only news about this coin will be displayed

### Tasks

- [x] create select dropdown element
- [x] put top-100 coins from coinmarketcap into the select element
- [x] change API request depending on chosen coin
- [x] display news depending on chosen coin

### Sizing/Complexity

**M**

**Comment by actyvystom** [comment]
Hey Oleksandr, a nice one 🙂 
A few comments: 
- your acceptance criteria should also describe what happens if a user selects a certain cryptocurrency
- looks like you already implemented it as this is a screenshot of your app... 🤔

**Comment by sashameniakin** [comment]
now only select is working, without functionality

**Comment by actyvystom** [comment]
Alright, please change the title in the Headline (it's still default User Story Title) and I will approve 😉

**Comment by sashameniakin** [comment]
thank you!
