### ISSUE TITLE
09 PopUp Picture for Metamask

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#17]
### Value Proposition

**As a** User
 **I need** to see session info and buttons on the pop-up picture
**to be able to** have his own overview about the specific information he needs and switch the networks.

### Description

<img width="372" alt="Bildschirmfoto 2022-12-09 um 15 16 00" src="https://user-images.githubusercontent.com/110241401/206721912-b4315449-43d9-4467-a4f2-f42621c16352.png">
<img width="587" alt="Bildschirmfoto 2022-12-09 um 15 17 37" src="https://user-images.githubusercontent.com/110241401/206722204-90a68d16-8333-4622-baf4-e5ea7c4f2f95.png">

### Acceptance Criteria

- [x] user can open pop-up picture with the button in the middle of the navbar
- [x] user can see info about currently metamask session
- [x] user can switch blockchain networks with the button 

### Tasks

- [x] create Pop-up picture
- [x] create function, that opens pop-up with button in the middle of the navbar
- [x] display info about currently metamask session
- [x] display buttons **switch to ...**
- [x] create functions, that switch metamask to the selected blockchain network

### Sizing/Complexity

**M**
