### ISSUE TITLE
10 Tasks/Add task

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#19]
### Value Proposition

**As a** User
**I need** to add tasks
**to be able to** to keep all activities in form convenient for him.

### Description

<img width="593" alt="Bildschirmfoto 2022-12-12 um 09 26 17" src="https://user-images.githubusercontent.com/110241401/206997056-f14e7c86-61b9-4b7e-9c14-73e960b0a867.png">

### Acceptance Criteria

- [x] user should be able to open form, button **add activity**
- [x] user should be able to add blockchains

### Tasks

- [x] create button **add activity**
- [x] on click button **add activity** create form (see picture)
- [x] add select element, where user can add blockchains 
- [x] save data on click submit button

### Sizing/Complexity

**M**
