### ISSUE TITLE
03 Fetching API

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#2]
### Value Proposition

**As a** User 
**I need** to see the information from coinmarketcap.com and bing.com on the "home" page
**to be able to** have my own overview about the specific information I need.

### Description

![Image](https://user-images.githubusercontent.com/110241401/204283986-610dec90-e99d-4297-823d-64beddb29a8b.png)

### Acceptance Criteria

- [x] information from coinmarketcap.com should be fetched 
- [x] information from bing.com should be fetched
- [x] fetching data should be correctly displayed by using corresponding components
- [x] top-100 coins are displayed
- [x] news are displayed

### Tasks

- [x] switch to the new branch **feature/API** locally
- [x] fetch the _coinmarketcap_ API
- [x] create context for the API
- [x] console.log data from the API
- [x] fetch the bing.com API
- [x] create context for the API
- [x] console.log data from the API 
- [x] commit the changes

### Sizing/Complexity

** L **
