### ISSUE TITLE
12 Task Component

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#21]
### Value Proposition

**As a** User 
**I need** to add/delete/watch tasks 
**to be able to** keep my activities

### Description

![Image](https://user-images.githubusercontent.com/110241401/207580202-65d6d908-2035-41ee-8c21-547e0f640c65.png)

### Acceptance Criteria

- [x] 3 buttons: delete task, see details, move to archive
- [x] user can add tasks
- [x] user can delete/watch tasks

### Tasks

- [x] open branch **feature/task**
- [x] create task component
- [x] connect data from form to task component
- [x] add function **delete task**
- [x] add function **see details**
- [x] add button **move to archive** (currently without function)

### Sizing/Complexity

**M**
