### ISSUE TITLE
11 Metamask functions rework

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#22]
### Value Proposition

**As a** User
**I need** to use MM functions
**to be able to** see info he need

### Description

![Image](https://user-images.githubusercontent.com/110241401/207566485-b1753a33-9aa5-4607-906a-5a79acc4b9b0.png)![Image](https://user-images.githubusercontent.com/110241401/207566565-72529db3-9ab4-48aa-afb9-82a2d48f2fcf.png)![Image](https://user-images.githubusercontent.com/110241401/207566514-1aa6be66-aadc-4d3a-80ae-1abbd2c13790.png)

### Acceptance Criteria

- [x] if user don't have MMwallet installed, app show him popup picture with link to install
- [x] if user already has MMwallet installed, app show him MMaddress and Blockchain in the Header
- [x] user should see ...Loading while he sign in
- [x] user should see if he change address or blockchain
- [x] the button "connect MM" in the middle of the navbar is colorful, when MM connected, and without color when MM disconnected

### Tasks

- [x] create popup picture with link to install Metamask by pressing button in the middle of the navbar
- [x] add functionality to show MMaddress and Blockchain in the Header
- [x] add functionality to show ...Loading, while user sign in to MM

### Sizing/Complexity

**M**

**Comment by sashameniakin** [comment]
Hi Kirsten, first of all, thanks for the comment! It's actually "to-do-list" button, you are right, the "connect metamask button" is that one -> 
<img width="133" alt="Bildschirmfoto 2022-12-14 um 12 45 08" src="https://user-images.githubusercontent.com/110241401/207587310-564e34b4-cef7-41dc-bc21-50e32ca5a341.png">
it will be always highlighted if metamask connected is, regardless of other buttons
