### ISSUE TITLE
13 Tasks Functionality and Drap&Drop

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#23]
### Value Proposition

**As a** User
**I need** to interact with the tasks
**to have** good experience with the app

### Description
<img width="730" alt="Bildschirmfoto 2022-12-16 um 14 09 51" src="https://user-images.githubusercontent.com/110241401/208106572-32d9adfd-fd25-45bb-9e25-43baac905908.png">
<img width="730" alt="Bildschirmfoto 2022-12-16 um 14 10 13" src="https://user-images.githubusercontent.com/110241401/208106586-347a5da5-62e5-4610-b305-e6b52fa2a9fe.png">
<img width="612" alt="Bildschirmfoto 2022-12-16 um 14 11 15" src="https://user-images.githubusercontent.com/110241401/208106607-131a05e9-f0e7-48b5-a9fc-b87b974c689f.png">

### Acceptance Criteria

- [x] user can see the details of the task
- [x] user can mark task like "done task"
- [x] user can drag and drop tasks like he wants
- [x] user can see in the progress bar how many tasks he has more, and how many already done

### Tasks

- [x] add function **see the details**
- [x] add function **done**
- [x] add drap&drop dunctionality
- [x] add progress bar function

### Sizing/Complexity

**M**
