### ISSUE TITLE
14 Dashboard/Funds Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#25]
### Value Proposition

**As a** User
**I need** to use the Dashboard
**to be able to** manage his funds

### Description

<img width="764" alt="Bildschirmfoto 2022-12-23 um 23 36 25" src="https://user-images.githubusercontent.com/110241401/209411205-f21fbd7f-7b24-4308-8443-4dbb506435ae.png">

### Acceptance Criteria

- [x] user can select coin and see the coin name and price
- [x] user can set the amount of the coin he want to buy/sell
- [x] user can use buy/sell buttons to add/remove coins, amount to the arrays

### Tasks

- [x] create **Dashboard** component
- [x] create select list to select and show the coin
- [x] create two options: **buy**, **sell** with buttons and inputs fields
- [x] create logic for buy and sell coins

### Sizing/Complexity

**M**
