### ISSUE TITLE
15 Transactions/Funds Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#26]
### Value Proposition

**As a** User
**I need** to see all my transactions
**to be able to** manage my funds

### Description

<img width="764" alt="Bildschirmfoto 2022-12-23 um 23 36 43" src="https://user-images.githubusercontent.com/110241401/209411540-6b81b071-2d46-4715-ac63-c47ffec98d4b.png">

### Acceptance Criteria

- [x] user can see all transaction
- [x] add transaction after pressing buttons **buy**, **sell**

### Tasks

- [x] create **transaction** component
- [x] create logic add transaction after every buy/sell action of the user

### Sizing/Complexity

** S **
