### ISSUE TITLE
16 Diagram/Funds Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#27]
### Value Proposition

**As a** User
**I need** to have information about my investments
**to be able to** manage my funds

### Description

<img width="501" alt="Bildschirmfoto 2022-12-26 um 21 16 54" src="https://user-images.githubusercontent.com/110241401/209581039-4efbf7be-6052-4cf8-b026-48af1c5c0027.png">

### Acceptance Criteria

- [x] user can add and remove coins from digram by pressing buttons **buy**/**sell** on dashboard
- [x] user can see legend on the left side and switch on/off coins from the diagram
- [x] user can see 3 diagrams:
- [x] 1. diagram outside - amount of coins user have - on hover tooltip
- [x] 2. diagram in the middle - worth of user's coins in dollars at the buy moment - on hover tooltip
- [x] 3. diagram inside -  worth of user's coins in dollars in actual moment - on hover tooltip
- [x] user can see message how to use diagram by pressing "hi there" button

### Tasks

- [x] create **diagram** component
- [x] create 3 diagrams inside each other with chartjs
- [x] create legend for the diagrams
- [x] connect diagrams with data from dashboard
- [x] create "hi there"button for the user help

### Sizing/Complexity

**L**
