### ISSUE TITLE
17 Bar/Funds Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#29]
### Value Proposition

**As a** User
**I need** to see profit/loss 
**to be able to** manage his funds better

### Description

<img width="640" alt="Bildschirmfoto 2022-12-27 um 15 02 06" src="https://user-images.githubusercontent.com/110241401/209677574-5a95b51e-6b7d-468f-b83d-46c478251b68.png">

### Acceptance Criteria

- [x] user can see profit/loss in dollars live by every coin
- [x] user can see on hover tooltip (coin name, profit/loss)

### Tasks

- [x] create **Bar** component
- [x] create bar grafik with chartjs
- [x] connect data from dashboard to the bar 

### Sizing/Complexity

**M**
