### ISSUE TITLE
07 Connect Metamask

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#3]
### Value Proposition

**As a** User 
**I need** to login to my app with Metamask
**to be able to** to use the functions of the app

### Description

![Image](https://user-images.githubusercontent.com/110241401/206143712-feeef3ca-c199-4e99-a3b6-b47037da4319.png)
![Image](https://user-images.githubusercontent.com/110241401/206143829-a6364e6d-b1aa-4143-b31e-426938d893d7.png)
![Image](https://user-images.githubusercontent.com/110241401/206143890-6ddd64b0-ece5-4894-bcfc-9c8c47d468de.png)

### Acceptance Criteria

- [x] User should have possibility to sign in/out with Metamask
- [x] User should be redirect to the **profile** page after login and to the **login** page after log out
- [x] User should see Metamask address in the header
- [x] User should see session data on the **profile** page

### Tasks

- [x] create new branch **feature/Metamask**
- [x] create button login via Metamask on **login** page
- [x] create login function
- [x] display session data on the **profile page**
- [x] create log out button and Metamask address in the header

### Sizing/Complexity

**L**
