### ISSUE TITLE
18 Connect with MongoDB

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#31]
### Value Proposition

**As a** User
**I need** to save my tasks in database
**to be able to** look at my archive from time to time

### Description

Scribble / design or text

### Acceptance Criteria

- [x] user can press button **send to archive** on every task
- [x] after pressing the task will be send to the database/archive
- [x] user can delete task, but it will be saved in database
- [x] user can delete the task also from database by pressing corresponding button  in the archive popup
- [x] user can open popup with the button in the header and see all tasks saved in database

### Tasks

- [x] create connection to the MongoDB
- [x] create model for MongoDB
- [x] create popup **Archive**
- [x] create button **open archive** in the header
- [x] connect button to the popup
- [x] create functionality **send to the archive**

### Sizing/Complexity

** L**
