### ISSUE TITLE
19 Profile Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#32]
### Value Proposition

**As a** User
**I need** to see info about user 
**to be able to** manage my account

### Description

<img width="365" alt="Bildschirmfoto 2023-01-05 um 13 50 21" src="https://user-images.githubusercontent.com/110241401/210784086-9dc1d00c-45d1-48e5-ba6f-2f1d67510abc.png">

### Acceptance Criteria

- [x] user can see his foto from github
- [x] user can see his email from github
- [x] user can sign out with the button **sign out**

### Tasks

- [x] create field for the foto
- [x] create field for the email
- [x] create **sign out** button
- [x] create functionality for sign out

### Sizing/Complexity

** M **
