### ISSUE TITLE
20 Style refactoring

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#33]
### Value Proposition

**As a** User
**I need**  to use app at deferent screens

### Description

Scribble / design or text

### Acceptance Criteria

- [x] user can use app on the deferent screens
- [x] all element looking fine at deferent screens
- [x] background an whole screen

### Tasks

- [x] style refactoring
- [x] code refactoring
- [x] check all pages for Iphone SE screen

### Sizing/Complexity

** M **
