### ISSUE TITLE
21 Register Page/Function

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#38]
### Value Proposition

**As a** User 
**I need** to register in app
**to be able to** access data

### Description

<img width="275" alt="image" src="https://user-images.githubusercontent.com/110241401/215327490-5992dfa8-3939-4805-b7e6-c7865663e436.png">

### Acceptance Criteria

- [x] user can register in the app
- [x] if user already rigestered, "user exists" will be show
- [x] after registration "register successful" will be show

### Tasks

- [x] create register page with corresponding fields
- [x] create handle register functuion
- [x] create api to the MongoDB to save user register data
- [x] make password encrypted 
- [x] save user registration data to MongoDB
- [x] check, if user already was registered 

### Sizing/Complexity

** M **
