### ISSUE TITLE
22 Login Functionality/JWT token

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#39]
### Value Proposition

**As a** User
**I need** to login 
**to be able to** use the app

### Description

Scribble / design or text

### Acceptance Criteria

- [x] if user's email not found in database, alert "user not found"
- [x] if user's password is not correct, alert "password invalid"
- [x] if all fine, compare password with password in database, alert "login successful "

### Tasks

- [x] create login handle function
- [x] create api to MongoDB
- [x] create jwt token after login
- [x] show user data on profile page
- [x] save jwt token in local storage

### Sizing/Complexity

** M **
