### ISSUE TITLE
23 Logout Function/JWT expired

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#40]
### Value Proposition

**As a** User
**I need** logout
**to be able to** exit app

### Description

Scribble / design or text

### Acceptance Criteria

- [x] user can logout by pressing **log out** button

### Tasks

- [x] add logout function
- [x] redirect to login page after logout
- [x] delete jwt token after logout
- [x] keep user logged in until he press logout
- [x] create token expired after 10 minutes function

### Sizing/Complexity

**S**
