### ISSUE TITLE
02 Login Page and Welcome Page

### ISSUE THREAD

**Issue by sashameniakin** [sashameniakin/CapstoneProject#5]
### Value Proposition

**As a** User
 **I need** to log in 
**to be able to** have access to the main pages

### Description

<img width="235" alt="Bildschirmfoto 2022-11-29 um 14 34 06" src="https://user-images.githubusercontent.com/110241401/204542668-7e3a7bb4-f925-4684-a588-3ac74c047cfe.png"><img width="235" alt="Bildschirmfoto 2022-11-29 um 14 34 20" src="https://user-images.githubusercontent.com/110241401/204542704-0ac21893-cb08-4325-899e-24d29555f183.png">

### Acceptance Criteria

- [x] **go** button redirects to the **login** page
- [x] currently the **login** button should redirect to the **home** page, you don't need to login with username/password
- [x] **register** link and **login with GitHub** button don't have any functions for now

### Tasks

- [x] create **feature/welcome-login** branch
- [x] create **welcome** and **login** pages
- [x] create animation
- [x] create **go** button
- [x] create **login** page
- [x] link **go** button to the **login** page
- [x] create **email**/**password** fields
- [x] create **login** button
- [x] create **login with GitHub** button 
- [x] create **register** link
- [x] link **login** button to the **home** page 
- [x] commit everything, create pull request

### Sizing/Complexity

**M**
